### ISSUE TITLE
想联系您有偿解决问题

### ISSUE THREAD

**Issue by fishfree** [HackerYunen/HousekeepingProject#9]
你好！实在找不到您的联系方式，冒昧在此开个issue。很想联系您帮忙有偿解决这个问题：https://github.com/EtherDream/jsproxy/issues/310 我的邮箱 二七二八八一五二一 at qq

**Comment by HackerYunen** [comment]
这个问题只能请你另请高明了... 
很抱歉，我并没有什么好的实现方法。
